= パートタイム労働者就業規則 =
:awestruct-layout: base
:showtitle:
:prev_section: defining-frontmatter
:next_section: creating-pages
:homepage: https://besna.institute

== 改訂履歴 ==
[options="header"]
|=================================
^|日付 ^|施行・改訂
>|2021年3月31日 >|施行
|=================================

== 第１章 総則 ==

=== 第１条 目的 ===
. この規則は、株式会社BESNA研究所就業規則第○○条第○項に基づき、パートタイム労働者の労働条件、服務規律その他の就業に関することを定めるものである。
. この規則に定めないことについては、労働基準法その他の関係法令の定めるところによる。

=== 第２条 定義 ===
. この規則において「パートタイム労働者」とは、第２章の定めにより採用された者で所定労働時間が１日○時間以内、１週○○時間以内又は１カ月○○○時間以内の契約内容で採用された者をいう。

=== 第３条 規則の遵守 ===
. 会社及びパートタイム労働者は、この規則を守り、お互いに協力して業務の運営に当たらなければならない。

== 第２章 採用および労働契約 ==

=== 第４条 採用 ===
. 会社は、パートタイム労働者の採用に当たっては、就職希望者のうちから選考して採用する。

=== 第５条 労働契約の期間等 ===
. 会社は、労働契約の締結に当たって期間の定めをする場合には、３年（満60歳以上のパートタイム労働者との契約については５年）の範囲内で、契約時に本人の希望を考慮の上各人別に決定し、別紙の労働条件通知書で示す。
. 前項の場合において、当該労働契約の期間の満了後における当該契約に係る更新の有無を別紙の労働条件通知書で示す。
. 当該契約について更新する場合又はしない場合の判断の基準は、以下の事項とする。
... 契約期間満了時の業務量により判断する。
... 当該パートタイム労働者の勤務成績、態度により判断する。
... 当該パートタイム労働者の能力により判断する。
... 会社の経営状況により判断する。
... 従事している業務の進捗状況により判断する。

=== 第６条 労働条件の明示 ===
. 会社は、パートタイム労働者の採用に際しては、別紙の労働条件通知書及びこの規則の写しを交付して労働条件を明示する。

== 第３章 服務規律 ==

=== 第７条 服務 ===
. パートタイム労働者は、業務の正常な運営を図るため、会社の指示命令を守り、誠実に服務を遂行するとともに、次の各事項をよく守り、職場の秩序の保持に努めなければならない。
... 会社の名誉又は信用を傷つける行為をしないこと
... 会社、取引先等の機密を他に漏らさないこと
... みだりに遅刻、早退、私用外出及び欠勤をしないこと。やむを得ず遅刻、早退、私用外出及び欠勤をするときは、事前に上司に届け出ること
... 勤務時間中は、みだりに定められた場所を離れないこと
... 許可なく職務以外の目的で会社の施設、物品等を使用しないこと
... 職務を利用して自己の利益を図り、また不正な行為を行わないこと

== 第４章 労働時間、休憩及び休日 ==

=== 第８条 労働時間及び休憩 ===
. 始業及び終業の時刻並びに休憩時間は、次のとおりとする。 +
 始業時刻 ○時 +
 終業時刻 ○時 +
 休憩時間 ○時から○時まで
. 前項の規定にかかわらず、業務の都合その他やむを得ない事情により始業及び終業の時刻並びに休憩時間を繰り上げ又は繰り下げることがある。
. 休憩時間は、自由に利用することができる。

=== 第９条 休日 ===
. 休日は、次のとおりとする。
... 日曜日及び土曜日
... 国民の祝日（振替休日を含む。）及び国民の休日（５月４日）
... 年末年始（12月○○日より、１月○日まで）
... その他会社が指定する日

=== 第１０条 休日の振替 ===
. 前条の休日については、業務の都合上やむを得ない場合は、あらかじめ他の日と振り替えることがある。ただし、休日は４週間を通じ８日を下回らないものとする。

=== 第１１条 時間外及び休日労働 ===
. 会社は、第８条第１項で定める労働時間を超えて労働させ、また第９条で定める休日に労働させないものとする。
. 前項の規定にかかわらず、業務の都合上やむを得ない場合は、○○株式会社就業規則第○○条第○項に定める社員（以下「社員」という。）の所定労働時間を超えない範囲内で労働させることができる。

=== 第１２条 出退勤手続 ===
. パートタイム労働者は、出退勤に当たって、各自のタイムカードに、出退勤の時刻を記録しなければならない。
. タイムカードは自ら打刻し、他人にこれを依頼してはならない。

== 第５章 休暇等 ==

=== 第１３条 年次有給休暇 ===
1.:: ６カ月以上継続して勤務し、会社の定める所定労働日数の８割以上出勤したときは、次表のとおり年次有給休暇を与える。

[options=""]
|=================================
 2+^s| 7+^s| 雇入れの日から起算した継続勤務期間の区分に応ずる年次有給休暇の日数 
^s|週所定労働時間 ^s|週所定労働日数 ^s|６か月 ^s|１年６か月 ^s|２年６か月 ^s|３年６か月 ^s|４年６か月 ^s|５年６か月 ^s|６年６か月以上
2+>s| ３０時間以上 .2+>|１０日 .2+>|１１日 .2+>|１２日 .2+>|１４日 .2+>|１６日 .2+>|１８日 .2+>|２０日
 .5+^.<s|３０時間未満 >|５日 
>|４日 >|７日 >|８日 >|９日 >|１０日 >|１２日 >|１３日 >|１５日
>|３日 >|５日 >|６日 >|６日 >|８日 >|９日 >|１０日 >|１１日
>|２日|３日 >|４日 >|４日 >|５日 >|６日 >|６日 >|７日
>|１日 >|１日 >|２日 >|２日 >|２日 >|３日 >|３日 >|３日
|=================================


2.:: 年次有給休暇を取得しようとするときは、所定の用紙によりその期日を指定して事前に届け出るものとする。
3.:: パートタイム労働者が指定した期日に年次有給休暇を取得すると事業の正常な運営に著しく支障があると認められるときは、他の日に変更することがある。
4.:: 前項の規定にかかわらず、従業員の過半数を代表する者との協定により、各パートタイム労働者の有する年次有給休暇日数のうち５日を超える部分について、あらかじめ期日を指定して計画的に与えることがある。
5.:: 当該年度の年次有給休暇で取得しなかった残日数については、翌年度に限り繰り越される。

=== 第１４条 年次有給休暇の時間単位での付与 ===
. 労使協定に基づき、前条の年次有給休暇の日数のうち、１年について５日の範囲内で、次により時間単位の年次有給休暇（以下「時間単位年休」という。）を付与する。
... 時間単位年休付与の対象者は、すべてのパートタイム労働者とする。
... 時間単位年休を取得する場合の、１日の年次有給休暇に相当する時間数は、以下のとおりとする。
..... 所定労働時間が５時間を超え６時間以下の者・・・６時間
..... 所定労働時間が６時間を超え７時間以下の者・・・７時間
..... 所定労働時間が７時間を超え８時間以下の者・・・８時間
... 時間単位年休は１時間単位で付与する。
... 本条の時間単位年休に支払われる賃金額は、所定労働時間労働した場合に支払われる通常の賃金の１時間当たりの額に、取得した時間単位年休の時間数を乗じた額とする。
... 上記以外の事項については、前条の年次有給休暇と同様とする。

=== 第１５条 産前産後の休業 ===
. ６週間（多胎妊娠の場合は１４週間）以内に出産する予定のパートタイム労働者は、請求によって休業することができる。
. 産後８週間を経過しないパートタイム労働者は就業させない。ただし、産後６週間を経過したパートタイム労働者から請求があった場合には、医師が支障がないと認めた業務に就かせることができる。

=== 第１６条 育児時間等 ===
. 生後１年未満の子を育てるパートタイム労働者から請求があったときは、休憩時間のほか１日について２回、１回について３０分の育児時間を与える。
. 生理日の就業が著しく困難なパートタイム労働者から請求があったときは、必要な期間休暇を与える。

=== 第１７条 妊娠中及び出産後の健康管理に関する措置 ===
. 妊娠中又は出産後１年以内のパートタイム労働者が母子保健法の規定による健康診査等のために勤務時間内に通院する必要がある場合は、請求により次の範囲で通院のための休暇を認める。ただし、医師又は助産師（以下「医師等」という。）の指示がある場合は、その指示による回数を認める。
... 妊娠２３週まで ４週間に１回
... 妊娠２４週から３５週まで ２週間に１回
... 妊娠３６週以降 １週間に１回
. 妊娠中のパートタイム労働者に対し、通勤時の混雑が母体の負担になると認められる場合は、本人の請求により始業時間を３０分繰下げ、終業時間を３０分繰上げることを認める。ただし、本人の請求により合計１日１時間以内を限度として繰下げ又は繰上げ時間の調整を認める。
. 妊娠中のパートタイム労働者が業務を長時間継続することが身体に負担になる場合、本人の請求により所定の休憩以外に適宜休憩をとることを認める。
. 妊娠中及び出産後１年以内のパートタイム労働者が、健康診査等を受け医師等から指導を受けた場合は、その指導事項を守ることができるようにするために次のことを認める。
... 作業の軽減
... 勤務時間の短縮
... 休業

=== 第１８条 育児休業 ===
. 育児のために休業することを希望するパートタイム労働者（日雇パートタイム労働者を除く）であって、１歳に満たない子と同居し、養育する者は、申出により、育児休業をすることができる。
. 配偶者がパートタイム労働者と同じ日から又はパートタイム労働者より先に育児休業をしている場合、パートタイム労働者は、子が１歳２か月に達するまでの間で、出生日以後の産前・産後休業期間と育児休業期間との合計が1年を限度として、育児休業をすることができる。
. 次のいずれにも該当するパートタイム労働者は、子の１歳の誕生日から１歳６か月に達するまでの間で必要な日数について育児休業をすることができる。なお、休業を開始しようとする日は、原則として子の１歳の誕生日に限るものとする。
... パートタイム労働者又は配偶者が原則として子の1歳誕生日の前日に育児休業をしていること
... 次のいずれかの事情があること
..... 保育所に入所を希望しているが、入所できない場合
..... パートタイム労働者の配偶者であって育児休業の対象となる子の親であり、1歳以後育児に当たる予定であった者が、死亡、負傷、疾病等の事情により子を養育することが困難になった場合
. 育児休業をすることを希望するパートタイム労働者は、原則として、育児休業を開始しようとする日の１か月前（前項に基づく休業の場合は、２週間前）までに、育児休業申出書を人事担当者に提出することにより申し出るものとする。
. 育児休業申出書が提出されたときは、会社は速やかに当該育児休業申出書を提出した者に対し、育児休業取扱通知書を交付する。

=== 第１９条 介護休業 ===
. 要介護状態にある家族を介護するパートタイム労働者（日雇パートタイム労働者を除く）は、申出により、介護を必要とする家族1
人につき、要介護状態ごとに１回、のべ９３日間までの範囲内で介護休業をすることができる。
. 要介護状態にある家族とは、負傷、疾病又は身体上若しくは精神上の障害により、２週間以上の期間にわたり常時介護を必要とする状態にある次の者をいう。
... 配偶者、父母、子、配偶者の父母
... 同居し、かつ扶養している祖父母、兄弟姉妹、孫
. 介護休業をすることを希望するパートタイム労働者は、原則として、介護休業を開始しようとする日の２週間前までに、介護休業申出書を人事担当者に提出することにより申し出るものとする。
. 介護休業申出書が提出されたときは、会社は速やかに当該介護休業申出書を提出した者に対し、介護休業取扱通知書を交付する。

=== 第２０条 子の看護休暇 ===
. 小学校就学の始期に達するまでの子を養育するパートタイム労働者（日雇パートタイム労働者を除く）は、負傷し、又は疾病にか
かった当該子の世話をするために、又は当該子に予防接種や健康診断を受けさせるために、就業規則第１３条に規定する年次有給休暇とは別に、当該子が１人の場合は１年間につき５日、２人以上の場合は1年間につき１０日を限度として、子の看護休暇を取得することができる。

=== 第２１条 介護休暇 ===
. 要介護状態にある家族の介護その他の世話をするパートタイム労働者（日雇パートタイム労働者を除く）は、就業規則第１３条に規定
する年次有給休暇とは別に、当該家族が１人の場合は１年間につき５日、２人以上の場合は1年間につき１０日を限度として、介護休暇を取得することができる。

=== 第２２条 所定外労働の免除 ===
. ３歳に満たない子を養育するパートタイム労働者（日雇パートタイム労働者を除く）が当該子を養育するために申し出た場合には、事業の正常な運営に支障がある場合を除き、所定労働時間を超えて労働をさせることはない。

=== 第２３条 時間外労働及び深夜業の制限 ===
. 小学校就学の始期に達するまでの子を養育するパートタイム労働者が当該子を養育するため又は要介護状態にある家族を介護するパ
ートタイム労働者が当該家族を介護するために申し出た場合には、事業の正常な運営に支障がある場合を除き、１か月について２４時間、１年について１５０時間を超えて時間外労働をさせること又は深夜に労働させることはない。

=== 第２４条 育児・介護のための短時間勤務 ===
. ３歳に満たない子を養育するパートタイム労働者又は第19条第２項に定める要介護状態にある家族を介護するパートタイム労働者
（日雇パートタイム労働者を除く）は、申し出ることにより、１日の所定労働時間を６時間まで短縮する短時間勤務をすることができる。
. 育児のための短時間勤務をしようとする者は、1回につき1年以内（ただし、子が3歳に達するまで）の期間について、短縮を開始しようとする日（短縮開始予定日）及び短縮を終了しようとする日（短縮終了予定日）を明らかにして、原則として、短縮開始予定日の１か月前までに、短時間勤務申出書により人事担当者に申し出なければならない。
. 介護のための短時間勤務をしようとする者は、１回につき９３日（その対象家族について介護休業をした場合又は異なる要介護状態について短時間勤務の適用を受けた場合は、９３日からその日数を控除した日数）以内の期間について、短縮開始予定日及び短縮終了予定日を明らかにして、原則として、短縮開始予定日の２週間前までに、人事担当者に申し出なければならない。

=== 第２５条 ===
. 育児・介護休業、子の看護休暇、介護休暇、育児のための所定外労働の免除、育児・介護のための時間外労働及び深夜業の制限、育
児短時間勤務並びに介護短時間勤務に関して、この規則に定めのないことについては、育児・介護休業法その他の法令の定めるところによる。

== 第６章 賃金 ==

=== 第２６条 賃金 ===
. 賃金は、次のとおりとする。
... 基本給 時間給とし、職務内容、成果、能力、経験等を考慮して各人別に決定する。
... 諸手当 +
通勤手当 通勤に要する実費を支給する。ただし、自転車や自動車などの交通用具を使用しているパートタイム労働者については、別に定めるところによる。 +
皆勤手当 当該賃金計算期間中の皆勤者に支給する。 月額 ○円 +
所定時間外労働手当 第８条第１項の所定労働時間を超えて労働させたときは、次の算式により計算して支給する。
..... １か月６０時間以下の時間外労働について +
基本給×1.25×時間外労働時間数 +
皆勤手当÷１年を平均した月所定労働時間数×1.25×時間外労働時間数
..... １か月６０時間を超える時間外労働について +
基本給×1.50×時間外労働時間数 +
皆勤手当÷１年を平均した月所定労働時間数×1.50×時間外労働時間数

休日労働手当 第９条の所定休日に労働させたときは、次の算式により計算して支給する。 +
基本給×1.35×休日労働時間数 +
皆勤手当÷１年を平均した月所定労働時間数×1.35×休日労働時間数 +
深夜労働手当 午後10時から午前5時までの間に労働させたときは、次の算式により計算して支給する。 +
基本給×0.25×深夜労働時間数 +
皆勤手当÷１年を平均した月所定労働時間数×0.25×深夜労働時間数

=== 第２７条 休暇等の賃金 ===
. 第１３条第１項で定める年次有給休暇については、所定労働時間労働したときに支払われる通常の賃金を支給する。
. 第１５条で定める産前産後の休業期間については、有給（無給）とする。
. 第１６条第１項で定める育児時間については、有給（無給）とする。
. 第１６条第２項で定める生理日の休暇については、有給（無給）とする。
. 第１７条第１項で定める時間内通院の時間については、有給（無給）とする。
. 第１７条第２項で定める遅出、早退により就業しない時間については、有給（無給）とする。
. 第１７条第３項で定める勤務中の休憩時間については、有給（無給）とする。
. 第１７条第４項で定める勤務時間の短縮により就業しない時間及び休業の期間については、有給（無給）とする。
. 第１８条で定める育児休業の期間については、有給（無給）とする。
. 第１９条で定める介護休業の期間については、有給（無給）とする。
. 第２０条で定める看護休暇の期間については、有給（無給）とする。
. 第２１条で定める介護休暇の期間については、有給（無給）とする。
. 第２３条で定める深夜業の免除により就業しない時間については、有給（無給）とする。
. 第２４条で定める短時間勤務により就業しない時間については、有給（無給）とする。

=== 第２８条 欠勤等の扱い ===
. 欠勤、遅刻、早退、及び私用外出の時間数に対する賃金は支払わないものとする。この場合の時間数の計算は、分単位とする。

=== 第２９条 賃金の支払い ===
. 賃金は、前月○○日から当月○○日までの分について、当月○○日（支払日が休日に当たる場合はその前日）に通貨で直接その金額
を本人に支払う。
. 次に掲げるものは賃金から控除するものとする。
... 源泉所得税
... 住民税
... 雇用保険及び社会保険の被保険者については、その保険料の被保険者の負担分
... その他、従業員の過半数を代表する者との書面による協定により控除することとしたもの

=== 第３０条 昇給 ===
. 1 年以上勤続し、成績の優秀なパートタイム労働者については、その勤務成績、職務遂行能力等を考慮し昇給を行う。
. 昇給は、原則として年１回とし、○月に実施する。

=== 第３１条 賞与 ===
. 毎年○月○日及び○月○日に在籍し、○カ月以上勤続したパートタイム労働者に対しては、その勤務成績、職務内容等を考慮し賞与を支給する。
. 賞与は、原則として年２回、○月○日及び○月○日（支払日が休日に当たる場合はその前日）に支給する。
. 支給額及び支給基準は、その期の会社の業績を考慮してその都度定める。

=== 第３２条 退職金 ===
. 勤続○年以上のパートタイム労働者が退職し、又は解雇されたときは、退職金を支給する。ただし第48条第２項により懲戒解雇された場合は、退職金の全部又は一部を支給しないことがある。

=== 第３３条 退職金額等 ===
. 退職金は、退職又は解雇時の基本給に勤続年数に応じて定めた別表（略）の支給率を乗じて計算した金額とする。
. 退職金は、支給事由の生じた日から○カ月以内に退職したパートタイム労働者（死亡した場合はその遺族）に支払う。

== 第７章 退職、雇止め及び解雇 ==

=== 第３４条 退職 ===
. パートタイム労働者が次のいずれかに該当するときは、退職とする。
... 労働契約に期間の定めがあり、かつ、労働条件通知書にその契約の更新がない旨あらかじめ示されている場合は、その期間が満了したとき
... 本人の都合により退職を申し出て会社が認めた時、又は退職の申し出をしてから１４日を経過したとき
... 本人が死亡したとき
. パートタイム労働者が、退職の場合において、使用期間、業務の種類、その事業における地位、賃金又は退職の事由（退職の事由が解雇の場合はその理由を含む。）について証明書を請求した場合は、遅滞なくこれを交付する。

=== 第３５条 雇止め ===
. 労働契約に期間の定めがあり、労働条件通知書にその契約を更新する場合がある旨をあらかじめ明示していたパートタイム労働者の
労働契約を更新しない場合には、尐なくとも契約が満了する日の３０日前までに予告する。
. 前項の場合において、当該パートタイム労働者が、雇止めの予告後に雇止めの理由について証明書を請求した場合には、遅滞なくこれを交付する。雇止めの後においても同様とする。

=== 第３６条 解雇 ===
. パートタイム労働者が、次のいずれかに該当するときは解雇する。この場合において、尐なくとも３０日前に予告をするか又は予告に代えて平均賃金の３０日分以上の解雇予告手当を支払う。
... 勤務成績又は業務能率が著しく不良で、向上の見込みがなく、他の職務にも転換できない等、就業に適さないと認められたとき
... 業務上の負傷又は疾病による療養の開始後３年を経過しても当該負傷又は疾病が治らない場合であって、パートタイム労働者が傷病補償年金を受けているとき又は受けることとなったとき（会社が打切り補償を支払ったときを含む。）
... 身体又は精神に障害がある場合で、適正な雇用管理を行い、雇用の継続に配慮してもなお業務に耐えられないと認められたとき
... 事業の運営上やむを得ない事情又は天災事変その他これに準ずるやむを得ない事情により、事業の継続が困難となったとき又は事業の縮小・転換又は部門の閉鎖等を行う必要が生じ、他の職務に転換させることが困難なとき
... その他前各号に準ずるやむを得ない事由があるとき
. 前項の予告の日数は、平均賃金を支払った日数だけ短縮する。
. パートタイム労働者が、解雇の予告がされた日から退職の日までの間に当該解雇の理由について証明書を請求した場合は、遅滞なくこれを交付する。

== 第８章 福利厚生等 ==

=== 第３７条 福利厚生 ===
. 会社は、福利厚生施設の利用等福利厚生については、社員と同様の取り扱いをする。

=== 第３８条 雇用保険等 ===
. 会社は、雇用保険、健康保険及び厚生年金保険の被保険者に該当するパートタイム労働者については、必要な手続きをとる。

=== 第３９条 教育訓練の実施 ===
. 会社は、社員に実施する教育訓練で当該社員が従事する職務の遂行に必要な能力を付与するものについては、職務内容が同一のパー
トタイム労働者に対して、社員と同様に実施する。
. 会社は、前項のほか、パートタイム労働者の職務内容、成果、能力、経験等に応じ教育訓練を実施する。

== 第９章 安全衛生及び災害補償 ==

=== 第４０条 安全衛生の確保 ===
. 会社は、パートタイム労働者の作業環境の改善を図り安全衛生教育、健康診断の実施その他必要な措置を講ずる。
. パートタイム労働者は、安全衛生に関する法令、規則並びに会社の指示を守り、会社と協力して労働災害の防止に努めなければならない。

=== 第４１条 健康診断 ===
. 引き続き１年以上（労働安全衛生規則第１３条第１項第２号に掲げる業務に従事する者については６カ月以上）使用され、又は使用することが予定されているパートタイム労働者に対しては、採用の際及び毎年定期に健康診断を行う。
. 有害な業務に従事するパートタイム労働者に対しては、特殊健康診断を行う。

=== 第４２条 安全衛生教育 ===
. パートタイム労働者に対し、採用の際及び配置換え等により作業内容を変更した際には、必要な安全衛生教育を行う。

=== 第４３条 災害補償 ===
. パートタイム労働者が業務上の事由若しくは通勤により負傷し、疾病にかかり又は死亡した場合は、労働者災害補償保険法に定める
保険給付を受けるものとする。
. パートタイム労働者が業務上負傷し又は疾病にかかり療養のため休業する場合の最初の３日間については、会社は平均賃金の60％の休業補償を行う。

== 第１０章 社員への転換 ==

=== 第４４条 社員への転換 ===
. １年以上勤続し、社員への転換を希望するパートタイム労働者については、次の要件を満たす場合、社員として採用し、労働契約を
締結するものとする。
... 1日８時間、１週４０時間の勤務ができること
... 所属長の推薦があること
... 面接試験に合格したこと
. 前項の場合において、会社は当該パートタイム労働者に対して必要な教育訓練を行う。
. 年次有給休暇の付与日数の算定及び退職金の算定において、パートタイム労働者としての勤続年数を通算する。
. 転換時期は毎年４月１日とする。

== 第１１章 無期労働契約への転換 ==

=== 第４５条 無期労働契約への転換 ===
. 期間の定めのある労働契約で雇用するパートタイム労働者のうち、通算契約期間が５年を超える者は、別に定める様式で申込むことにより、現在締結している有期労働契約の契約期間の末日の翌日から、期間の定めのない労働契約での雇用に転換することができる。
. 前項の通算契約期間は、平成２５年４月１日以降に開始する有期労働契約の契約期間を通算するものとし、現在締結している有期労働契約については、その末日までの期間とする。ただし、労働契約が締結されていない期間が連続して６ヶ月以上ある社員については、それ以前の契約期間は通算契約期間に含めない。
. この規則に定める労働条件は、第１項の規定により期間の定めのない労働契約での雇用に転換した後も引き続き適用する。ただし、無期労働契約へ転換した従業員に係る定年は、満○歳とし、定年に達した日の属する月の末日をもって退職とする。

== 第１２章 表彰及び懲戒 ==

=== 第４６条 表彰 ===
. パートタイム労働者が次の各号のいずれかに該当するときは表彰をする。
... 永年勤続し、勤務成績が優れているとき（永年勤続は○年、○年、○年とする）
... 勤務成績が優れ、業務に関連して有益な改良、改善、提案等を行い、業績の向上に貢献したとき
... 重大な事故、災害を未然に防止し、又は事故災害等の非常の際に適切な行動により災害の拡大を防ぐ等特別の功労があったとき
... 人命救助その他社会的に功績があり、会社の名誉を高めたとき
... その他前各号に準ずる行為で、他の従業員の模範となり、又は会社の名誉信用を高めたとき

=== 第４７条 表彰の種類 ===
. 表彰は、表彰状を授与し、あわせて表彰の内容により賞品もしくは賞金の授与、特別昇給又は特別休暇を付与する。
. 表彰は、個人又はグループを対象に、原則として会社創立記念日に行う。

=== 第４８条 懲戒の種類 ===
. 会社は、その情状に応じ次の区分により懲戒を行う。
... け ん 責 始末書を提出させ将来を戒める。
... 減 給 始末書を提出させ減給する。ただし、減給は、１回の額が平均賃金の１日分の５割（２分の１）を超え、総額が１賃金支払期間における賃金の１割（１０分の１）を超えることはない。
... 出勤停止 始末書を提出させるほか、○日間を限度として出勤を停止し、その間の賃金は支給しない。
... 懲戒解雇 即時に解雇する。

=== 第４９条 懲戒の事由 ===
. パートタイム労働者が次のいずれかに該当するときは、けん責、減給又は出勤停止とする。
... 正当な理由なく無断欠勤○日以上に及ぶとき
... 正当な理由なくしばしば欠勤、遅刻、早退をするなど勤務に熱心でないとき
... 過失により会社に損害を与えたとき
... 素行不良で会社内の秩序又は風紀を乱したとき
... 会社内において、性的な言動によって他人に不快な思いをさせたり、職場の環境を悪くしたとき
... 会社内において、性的な関心を示したり、性的な行為をしかけたりして、他の従業員の業務に支障を与えたとき
... その他この規則に違反し、又は前各号に準ずる不適切な行為があったとき
. パートタイム労働者が次のいずれかに該当するときは、懲戒解雇とする。
... 正当な理由なく無断欠勤○日以上に及び、出勤の督促に応じないとき
... 正当な理由なく欠勤、遅刻、早退を繰り返し、○回にわたって注意を受けても改めないとき
... 会社内における窃取、横領、傷害等刑法犯に該当する行為があったとき、又はこれらの行為が会社外で行われた場合であっても、それが著しく会社の名誉若しくは信用を傷つけたとき
... 故意又は重大な過失により会社に損害を与えたとき
... 素行不良で著しく会社内の秩序又は風紀を乱したとき
... 職責を利用して交際を強要したり、性的な関係を強要したとき
... 重大な経歴詐称があったしたとき
... その他この規則に違反し、又は前各号に準ずる不適切な行為があったとき

 附則
この規則は、平成○年○月○日から実施する